// /**
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/ppyQMepURfK
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */

// /** Add fonts into your Next.js project:

// import { Archivo } from 'next/font/google'

// archivo({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import { Button } from "~/components/ui/button"

// export function RepoSearchIdea() {
//   return (
//     <div className="container mx-auto px-4 py-8 md:px-6 lg:px-8">
//       <h1 className="text-3xl font-bold mb-6">Repositories</h1>
//       <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
//         <div className="bg-background rounded-lg shadow-md overflow-hidden">
//           <div className="bg-muted p-4 flex items-center">
//             <div className="flex-shrink-0 mr-4">
//               <img src="/placeholder.svg" alt="Owner Avatar" width={40} height={40} className="rounded-full" />
//             </div>
//             <div>
//               <h2 className="text-lg font-medium">shadcn/ui</h2>
//               <p className="text-muted-foreground text-sm">shadcn</p>
//             </div>
//           </div>
//           <div className="p-4">
//             <p className="text-muted-foreground mb-4">
//               Beautifully designed components that you can copy and paste into your apps.
//             </p>
//             <div className="flex items-center justify-between mb-4">
//               <div className="flex items-center gap-4">
//                 <div className="flex items-center gap-1">
//                   <GitBranchIcon className="w-4 h-4" />
//                   <span>10 branches</span>
//                 </div>
//                 <div className="flex items-center gap-1">
//                   <TagIcon className="w-4 h-4" />
//                   <span>25 releases</span>
//                 </div>
//                 <div className="flex items-center gap-1">
//                   <DoorOpenIcon className="w-4 h-4" />
//                   <span>100 issues</span>
//                 </div>
//                 <div className="flex items-center gap-1">
//                   <GitCommitVerticalIcon className="w-4 h-4" />
//                   <span>500 commits</span>
//                 </div>
//               </div>
//               <div className="flex items-center gap-1 text-muted-foreground text-sm">
//                 <CalendarIcon className="w-4 h-4" />
//                 <span>Created 2 years ago</span>
//                 <CalendarIcon className="w-4 h-4" />
//                 <span>Updated 1 month ago</span>
//               </div>
//             </div>
//             <div className="flex items-center justify-between mb-4">
//               <div className="flex items-center gap-2">
//                 <StarIcon className="w-5 h-5 fill-primary" />
//                 <span className="font-medium">20k</span>
//               </div>
//               <div className="flex items-center gap-2">
//                 <CodeIcon className="w-5 h-5 fill-primary" />
//                 <span className="font-medium">TypeScript</span>
//               </div>
//               <div className="flex items-center gap-2">
//                 <GitForkIcon className="w-5 h-5 fill-primary" />
//                 <span className="font-medium">5k</span>
//               </div>
//             </div>
//             <div className="flex items-center justify-between">
//               <div className="flex items-center gap-2">
//                 <img src="/placeholder.svg" alt="Organization Logo" width={32} height={32} className="rounded-full" />
//                 <div>
//                   <p className="text-sm font-medium">Vercel</p>
//                   <p className="text-xs text-muted-foreground">10k subscribers</p>
//                 </div>
//               </div>
//               <Button variant="outline" size="sm">
//                 View Repository
//               </Button>
//             </div>
//           </div>
//         </div>
//         <div className="bg-background rounded-lg shadow-md overflow-hidden">
//           <div className="bg-muted p-4 flex items-center">
//             <div className="flex-shrink-0 mr-4">
//               <img src="/placeholder.svg" alt="Owner Avatar" width={40} height={40} className="rounded-full" />
//             </div>
//             <div>
//               <h2 className="text-lg font-medium">shadcn/tailwindcss-radix</h2>
//               <p className="text-muted-foreground text-sm">shadcn</p>
//             </div>
//           </div>
//           <div className="p-4">
//             <p className="text-muted-foreground mb-4">Tailwind CSS components powered by Radix UI.</p>
//             <div className="flex items-center justify-between mb-4">
//               <div className="flex items-center gap-4">
//                 <div className="flex items-center gap-1">
//                   <GitBranchIcon className="w-4 h-4" />
//                   <span>5 branches</span>
//                 </div>
//                 <div className="flex items-center gap-1">
//                   <TagIcon className="w-4 h-4" />
//                   <span>10 releases</span>
//                 </div>
//                 <div className="flex items-center gap-1">
//                   <DoorOpenIcon className="w-4 h-4" />
//                   <span>50 issues</span>
//                 </div>
//                 <div className="flex items-center gap-1">
//                   <GitCommitVerticalIcon className="w-4 h-4" />
//                   <span>250 commits</span>
//                 </div>
//               </div>
//               <div className="flex items-center gap-1 text-muted-foreground text-sm">
//                 <CalendarIcon className="w-4 h-4" />
//                 <span>Created 1 year ago</span>
//                 <CalendarIcon className="w-4 h-4" />
//                 <span>Updated 2 weeks ago</span>
//               </div>
//             </div>
//             <div className="flex items-center justify-between mb-4">
//               <div className="flex items-center gap-2">
//                 <StarIcon className="w-5 h-5 fill-primary" />
//                 <span className="font-medium">5k</span>
//               </div>
//               <div className="flex items-center gap-2">
//                 <CodeIcon className="w-5 h-5 fill-primary" />
//                 <span className="font-medium">TypeScript</span>
//               </div>
//               <div className="flex items-center gap-2">
//                 <GitForkIcon className="w-5 h-5 fill-primary" />
//                 <span className="font-medium">1k</span>
//               </div>
//             </div>
//             <div className="flex items-center justify-between">
//               <div className="flex items-center gap-2">
//                 <img src="/placeholder.svg" alt="Organization Logo" width={32} height={32} className="rounded-full" />
//                 <div>
//                   <p className="text-sm font-medium">Vercel</p>
//                   <p className="text-xs text-muted-foreground">5k subscribers</p>
//                 </div>
//               </div>
//               <Button variant="outline" size="sm">
//                 View Repository
//               </Button>
//             </div>
//           </div>
//         </div>
//         <div className="bg-background rounded-lg shadow-md overflow-hidden">
//           <div className="bg-muted p-4 flex items-center">
//             <div className="flex-shrink-0 mr-4">
//               <img src="/placeholder.svg" alt="Owner Avatar" width={40} height={40} className="rounded-full" />
//             </div>
//             <div>
//               <h2 className="text-lg font-medium">shadcn/ui-components</h2>
//               <p className="text-muted-foreground text-sm">shadcn</p>
//             </div>
//           </div>
//           <div className="p-4">
//             <p className="text-muted-foreground mb-4">
//               A collection of high-quality React components built with Tailwind CSS.
//             </p>
//             <div className="flex items-center justify-between mb-4">
//               <div className="flex items-center gap-4">
//                 <div className="flex items-center gap-1">
//                   <GitBranchIcon className="w-4 h-4" />
//                   <span>8 branches</span>
//                 </div>
//                 <div className="flex items-center gap-1">
//                   <TagIcon className="w-4 h-4" />
//                   <span>15 releases</span>
//                 </div>
//                 <div className="flex items-center gap-1">
//                   <DoorOpenIcon className="w-4 h-4" />
//                   <span>75 issues</span>
//                 </div>
//                 <div className="flex items-center gap-1">
//                   <GitCommitVerticalIcon className="w-4 h-4" />
//                   <span>375 commits</span>
//                 </div>
//               </div>
//               <div className="flex items-center gap-1 text-muted-foreground text-sm">
//                 <CalendarIcon className="w-4 h-4" />
//                 <span>Created 1.5 years ago</span>
//                 <CalendarIcon className="w-4 h-4" />
//                 <span>Updated 3 months ago</span>
//               </div>
//             </div>
//             <div className="flex items-center justify-between mb-4">
//               <div className="flex items-center gap-2">
//                 <StarIcon className="w-5 h-5 fill-primary" />
//                 <span className="font-medium">10k</span>
//               </div>
//               <div className="flex items-center gap-2">
//                 <CodeIcon className="w-5 h-5 fill-primary" />
//                 <span className="font-medium">TypeScript</span>
//               </div>
//               <div className="flex items-center gap-2">
//                 <GitForkIcon className="w-5 h-5 fill-primary" />
//                 <span className="font-medium">2.5k</span>
//               </div>
//             </div>
//             <div className="flex items-center justify-between">
//               <div className="flex items-center gap-2">
//                 <img src="/placeholder.svg" alt="Organization Logo" width={32} height={32} className="rounded-full" />
//                 <div>
//                   <p className="text-sm font-medium">Vercel</p>
//                   <p className="text-xs text-muted-foreground">7.5k subscribers</p>
//                 </div>
//               </div>
//               <Button variant="outline" size="sm">
//                 View Repository
//               </Button>
//             </div>
//           </div>
//         </div>
//       </div>
//     </div>
//   )
// }

// function CalendarIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M8 2v4" />
//       <path d="M16 2v4" />
//       <rect width="18" height="18" x="3" y="4" rx="2" />
//       <path d="M3 10h18" />
//     </svg>
//   )
// }

// function CodeIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <polyline points="16 18 22 12 16 6" />
//       <polyline points="8 6 2 12 8 18" />
//     </svg>
//   )
// }

// function DoorOpenIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M13 4h3a2 2 0 0 1 2 2v14" />
//       <path d="M2 20h3" />
//       <path d="M13 20h9" />
//       <path d="M10 12v.01" />
//       <path d="M13 4.562v16.157a1 1 0 0 1-1.242.97L5 20V5.562a2 2 0 0 1 1.515-1.94l4-1A2 2 0 0 1 13 4.561Z" />
//     </svg>
//   )
// }

// function GitBranchIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <line x1="6" x2="6" y1="3" y2="15" />
//       <circle cx="18" cy="6" r="3" />
//       <circle cx="6" cy="18" r="3" />
//       <path d="M18 9a9 9 0 0 1-9 9" />
//     </svg>
//   )
// }

// function GitCommitVerticalIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M12 3v6" />
//       <circle cx="12" cy="12" r="3" />
//       <path d="M12 15v6" />
//     </svg>
//   )
// }

// function GitForkIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <circle cx="12" cy="18" r="3" />
//       <circle cx="6" cy="6" r="3" />
//       <circle cx="18" cy="6" r="3" />
//       <path d="M18 9v2c0 .6-.4 1-1 1H7c-.6 0-1-.4-1-1V9" />
//       <path d="M12 12v3" />
//     </svg>
//   )
// }

// function StarIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
//     </svg>
//   )
// }

// function TagIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z" />
//       <circle cx="7.5" cy="7.5" r=".5" fill="currentColor" />
//     </svg>
//   )
// }
